version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install -Dmaven.test.skip=true
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
 - target/VIA-app.war
   discard-paths: yes